version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: pd_nginx
    ports:
      - "8080:80"           # ← ブラウザは http://localhost:8080
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks: [pdnet]

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: pd_php
    volumes:
      - ./src:/var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks: [pdnet]

  mysql:
    image: mysql:8.0
    container_name: pd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3307:3306"         # ← ホスト競合回避。DBeaver等は3307へ
    volumes:
      - dbdata:/var/lib/mysql
    networks: [pdnet]

  node:
    image: node:20-alpine
    container_name: pd_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"         # ← Vite dev server (後で使う)
    command: sh -c "npm -v && tail -f /dev/null"
    networks: [pdnet]

volumes:
  dbdata:

networks:
  pdnet:
